### ISSUE TITLE
Install Script

### ISSUE THREAD

**Issue by mativillagra** [meltwater/lighter#38]

**Comment by mativillagra** [comment]
Hi, 

I'm trying to install this code on my local machine to give a try, I'm doing so create a lighter file on the root of my project, named lighter copy and paste you install script, modifying the LIGHTER_VERSION="0.15.1" 

I give run permissions to the script, but getting 

./lighter.sh: 6: ./lighter.sh: Bad substitution

Anyway the process, continues an create a target folder with the lighter-Linux-x86_64 binary. 

Next trying to used it I get,

$ ./lighter --help
./lighter: 6: ./lighter: Bad substitution
usage: lighter COMMAND [OPTIONS]...

Marathon deployment tool

positional arguments:
  {deploy,verify}       Available commands
    deploy              Deploy services to Marathon
    verify              Verify and generate Marathon configuration files

optional arguments:
  -h, --help            show this help message and exit
  -n, --noop            Execute dry-run without modifying Marathon [default:
                        False]
  -v, --verbose         Increase logging verbosity [default: False]
  -t TARGETDIR, --targetdir TARGETDIR
                        Directory to output rendered config files

Can you please tell me what I'm doing wrong. Thanks for the work, keep it up!!

**Comment by rasjoh** [comment]
@mativillagra Thanks for the input!

It should be bin/bash since there is a minor difference we seem to use here, or even "#!/usr/bin/env bash" should be a more portable shebang and should've been used
The script still works as you used it, although producing a warning.
I'll make the change to the example.

Regards, Rasmus
