### ISSUE TITLE
Python Package

### ISSUE THREAD

**Issue by nghgd** [meltwater/lighter#39]
Could this project be reorganized into a real python package? It's many times easier for users to work with.

Make a new repo from /src
Make a setup.py file in the root directory:

```
from setuptools import setup

setup(
    name='lighter',
    version='1.0.0',
    packages=['lighter'],
    scripts=[
        'scripts/lighter',
    ],
    install_requires=[
        'autopep8',
        'joblib',
        'mock',
        'flake8',
        'pyinstaller',
        'pynacl',
        'pyyaml',
        'requests',
        'packaging',
        'cffi',
    ],
)
```

Make a scripts/lighter file:

```
#!/usr/local/bin/python

import lighter.main as lighter

lighter.main()
```

Alter the lighter/main file:

Replace:

```
if __name__ == '__main__':
```

With:

```
def main():
```

At the end of the file, add:

```
if __name__ == '__main__':
    main()
```

Once submitted to pypi, users can easily install it on their machine with pip alone.

Here is an example of what the entire repo would look like:
[lighter.zip](https://github.com/meltwater/lighter/files/382114/lighter.zip)

**Comment by salimane** [comment]
@nghgd a pull request would be welcomed :)

**Comment by nghgd** [comment]
A pull request seems inappropriate to overwrite the entire repository. I also do not know what documentation or extras you wish to keep.

**Comment by salimane** [comment]
@nghgd just try and you will be surprised by the lovely response :)

**Comment by Solisol** [comment]
This repository is being deprecated and will no longer be maintained.
