### ISSUE TITLE
Enable Lighter to preserve custom instance count

### ISSUE THREAD

**Issue by rasjoh** [meltwater/lighter#41]
The instance count of a Marathon service can be modified by some other actor (e.g. manually or by an auto-scaler). Currently Lighter would overwrite the custom instance count on the next deployment.

Enable Lighter to preserve the custom instance count if it's externally changed. Lighter should still modify the instance count if it's not externally changed.

Example algoritm
- Add a com.meltwater.lighter.instances = N label on the service when Lighter deploys it. The label com.meltwater.lighter.instances should always be set by Lighter to what the service.config.instances is configured to in the yaml files.
- At next Lighter run, if com.meltwater.lighter.instances differs from prevVersion.instances then autoscaling has happened. In this case set service.config.instances = prevVersion.instances to preserve the autoscaled instance count.

**Comment by Solisol** [comment]
This repository is being deprecated and will no longer be maintained.
