### ISSUE TITLE
Support sending Graphite deployment event

### ISSUE THREAD

**Issue by perbergland-meltwater** [meltwater/lighter#46]
Just like what Lighter can already do for DataDog

http://obfuscurity.com/2014/01/Graphite-Tip-A-Better-Way-to-Store-Events

**Comment by mikljohansson** [comment]
http://graphite.readthedocs.io/en/latest/events.html
http://docs.grafana.org/reference/annotations/

Seems straight forward enough

**Comment by mikljohansson** [comment]
Solved by #48 and released in Lighter 0.17.0
