### ISSUE TITLE
Is this tool used in production?

### ISSUE THREAD

**Issue by christianparpart** [meltwater/lighter#56]
Hi all,

sorry if this title sounds a little offensive, but trying to get it to run feels slightly backstabbing. However, I am looking for a good deployment tool (ideally CLI) that we can use on top of our Marathon/Mesos cluster(s) and from the first look, `lighter` seems like a very good idea.

However, I noticed quite a few pains.
* the `Dockerfile` is not working at all and poorly respecting best practices
* the shell scripts (such as `/commone.sh` and `/lighter`  and `/test` use `set -x`, something you should only do while debugging your code - not in production.

I'd be willing to provide some PRs, however, I have proven zero knowledge in Python, also, done 3-liner PRs feels like we're all better off if you just `$EDITOR $thefile && git commit -a && git commit` yourself. Please correct me, if I can still be at help.

Last but not least,
will you continue using `lighter` in our own (production??) environment, or what will the expected TTL be?

Many thanks, and looking forward for your reply,
Christian.

**Comment by Solisol** [comment]
This repository is being deprecated and will no longer be maintained.
